import { notFound } from "next/navigation";
import { createClient } from "@supabase/supabase-js";
import type { Metadata } from "next";

// ── Helpers ───────────────────────────────────────────────

const SECTION_META: Record<string, { title: string }> = {
  executive_summary: { title: "Executive Summary" },
  audience_profiles: { title: "Audience Profiles" },
  positioning_and_differentiation: { title: "Positioning & Differentiation" },
  voice_and_tone_guide: { title: "Voice & Tone Guide" },
  content_pillars_and_topic_bank: { title: "Content Pillars & Topic Bank" },
  weekly_content_ecosystem: { title: "Weekly Content Ecosystem" },
  twelve_week_narrative_arc: { title: "12-Week Narrative Arc" },
  success_metrics: { title: "Success Metrics" },
};

const SECTION_ORDER = Object.keys(SECTION_META);

function createAdminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } },
  );
}

async function getSharedDocument(shareToken: string) {
  const supabase = createAdminClient();

  const { data: doc } = await supabase
    .from("strategy_documents")
    .select("id, company_id, content, version, generated_at, share_token")
    .eq("share_token", shareToken)
    .maybeSingle();

  if (!doc) return null;

  const { data: company } = await supabase
    .from("companies")
    .select("id, name")
    .eq("id", doc.company_id)
    .maybeSingle();

  return { doc, companyName: company?.name || "Untitled Company" };
}

// ── OG Metadata ───────────────────────────────────────────

type MetadataProps = { params: Promise<{ shareToken: string }> };

export async function generateMetadata({ params }: MetadataProps): Promise<Metadata> {
  const { shareToken } = await params;
  const result = await getSharedDocument(shareToken);

  if (!result) {
    return { title: "Strategy Not Found" };
  }

  const { companyName } = result;

  return {
    title: `Content Strategy \u2014 ${companyName}`,
    description: `Professional content strategy document for ${companyName}`,
    openGraph: {
      title: `Content Strategy \u2014 ${companyName}`,
      description: `Professional content strategy built with AGENCY Content Platform`,
    },
  };
}

// ── Page ──────────────────────────────────────────────────

type PageProps = { params: Promise<{ shareToken: string }> };

export default async function SharedStrategyPage({ params }: PageProps) {
  const { shareToken } = await params;
  const result = await getSharedDocument(shareToken);

  if (!result) {
    notFound();
  }

  const { doc, companyName } = result;
  const content = (doc.content || {}) as Record<string, string | null>;

  // Build ordered sections from the document content
  const sections = SECTION_ORDER.map((key) => ({
    key,
    title: SECTION_META[key].title,
    body: (content[key] as string) || "",
  })).filter((s) => s.body.length > 0);

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
      {/* Header bar */}
      <div className="border-b border-gray-200 bg-white">
        <div className="mx-auto max-w-3xl px-6 py-4 flex items-center justify-between">
          <div>
            <p className="text-[10px] font-bold tracking-widest text-gray-500 uppercase">
              Content Strategy
            </p>
            <h1 className="text-lg font-bold text-gray-900">{companyName}</h1>
          </div>
          <p className="text-xs text-gray-500">Powered by AGENCY</p>
        </div>
      </div>

      {/* Document body */}
      <div className="mx-auto max-w-3xl px-6 py-12 space-y-12">
        {sections.map((section, i) => (
          <section key={section.key}>
            <div className="flex items-center gap-3 mb-4">
              <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-900 text-xs font-bold text-white">
                {String(i + 1).padStart(2, "0")}
              </span>
              <h2 className="text-xl font-bold text-gray-900">{section.title}</h2>
            </div>
            <div className="prose prose-sm max-w-none text-gray-600">
              {section.body.split("\n\n").map((para, j) => (
                <p key={j}>{para}</p>
              ))}
            </div>
          </section>
        ))}

        {sections.length === 0 && (
          <div className="text-center py-20">
            <p className="text-gray-500 text-sm">This strategy document has no content yet.</p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="border-t border-gray-200 bg-gray-50">
        <div className="mx-auto max-w-3xl px-6 py-6 text-center">
          <p className="text-xs text-gray-500">
            Strategy document generated by <strong>AGENCY Content Platform</strong>
          </p>
          <a
            href="https://agency-review-portal.vercel.app"
            className="mt-1 inline-block text-xs text-violet-600 hover:text-violet-700"
          >
            Build your own content strategy &rarr;
          </a>
        </div>
      </div>
    </div>
  );
}
